/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TypingRouteImport } from './routes/typing'
import { Route as CodeExamExamIdRouteImport } from './routes/code-exam.$examId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalysisRouteImport } from './routes/dashboard.analysis'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAnalysisRouteImport } from './routes/teacher.analysis'
import { Route as TeacherCreateExamRouteImport } from './routes/teacher.create-exam'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherExamsExamIdRouteImport } from './routes/teacher.exams.$examId'
import { Route as TeacherResultsSubmissionIdRouteImport } from './routes/teacher.results.$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TypingRoute = TypingRouteImport.update({
  id: '/typing',
  path: '/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeExamExamIdRoute = CodeExamExamIdRouteImport.update({
  id: '/code-exam/$examId',
  path: '/code-exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalysisRoute = DashboardAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalysisRoute = TeacherAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCreateExamRoute = TeacherCreateExamRouteImport.update({
  id: '/create-exam',
  path: '/create-exam',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsExamIdRoute = TeacherExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsSubmissionIdRoute =
  TeacherResultsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => TeacherResultsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/exam': typeof ExamRoute
  '/exams': typeof ExamsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/typing': typeof TypingRoute
  '/code-exam/$examId': typeof CodeExamExamIdRoute
  '/dashboard/analysis': typeof DashboardAnalysisRoute
  '/teacher/analysis': typeof TeacherAnalysisRoute
  '/teacher/create-exam': typeof TeacherCreateExamRoute
  '/teacher/results': typeof TeacherResultsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/exams/$examId': typeof TeacherExamsExamIdRoute
  '/teacher/results/$submissionId': typeof TeacherResultsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/exams': typeof ExamsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/typing': typeof TypingRoute
  '/code-exam/$examId': typeof CodeExamExamIdRoute
  '/dashboard/analysis': typeof DashboardAnalysisRoute
  '/teacher/analysis': typeof TeacherAnalysisRoute
  '/teacher/create-exam': typeof TeacherCreateExamRoute
  '/teacher/results': typeof TeacherResultsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/exams/$examId': typeof TeacherExamsExamIdRoute
  '/teacher/results/$submissionId': typeof TeacherResultsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/exam': typeof ExamRoute
  '/exams': typeof ExamsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/typing': typeof TypingRoute
  '/code-exam/$examId': typeof CodeExamExamIdRoute
  '/dashboard/analysis': typeof DashboardAnalysisRoute
  '/teacher/analysis': typeof TeacherAnalysisRoute
  '/teacher/create-exam': typeof TeacherCreateExamRoute
  '/teacher/results': typeof TeacherResultsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/exams/$examId': typeof TeacherExamsExamIdRoute
  '/teacher/results/$submissionId': typeof TeacherResultsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/exam'
    | '/exams'
    | '/login'
    | '/signup'
    | '/teacher'
    | '/typing'
    | '/code-exam/$examId'
    | '/dashboard/analysis'
    | '/teacher/analysis'
    | '/teacher/create-exam'
    | '/teacher/results'
    | '/dashboard/'
    | '/teacher/'
    | '/teacher/exams/$examId'
    | '/teacher/results/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam'
    | '/exams'
    | '/login'
    | '/signup'
    | '/typing'
    | '/code-exam/$examId'
    | '/dashboard/analysis'
    | '/teacher/analysis'
    | '/teacher/create-exam'
    | '/teacher/results'
    | '/dashboard'
    | '/teacher'
    | '/teacher/exams/$examId'
    | '/teacher/results/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/exam'
    | '/exams'
    | '/login'
    | '/signup'
    | '/teacher'
    | '/typing'
    | '/code-exam/$examId'
    | '/dashboard/analysis'
    | '/teacher/analysis'
    | '/teacher/create-exam'
    | '/teacher/results'
    | '/dashboard/'
    | '/teacher/'
    | '/teacher/exams/$examId'
    | '/teacher/results/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExamRoute: typeof ExamRoute
  ExamsRoute: typeof ExamsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  TypingRoute: typeof TypingRoute
  CodeExamExamIdRoute: typeof CodeExamExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typing': {
      id: '/typing'
      path: '/typing'
      fullPath: '/typing'
      preLoaderRoute: typeof TypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-exam/$examId': {
      id: '/code-exam/$examId'
      path: '/code-exam/$examId'
      fullPath: '/code-exam/$examId'
      preLoaderRoute: typeof CodeExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analysis': {
      id: '/dashboard/analysis'
      path: '/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof DashboardAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analysis': {
      id: '/teacher/analysis'
      path: '/analysis'
      fullPath: '/teacher/analysis'
      preLoaderRoute: typeof TeacherAnalysisRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/create-exam': {
      id: '/teacher/create-exam'
      path: '/create-exam'
      fullPath: '/teacher/create-exam'
      preLoaderRoute: typeof TeacherCreateExamRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams/$examId': {
      id: '/teacher/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/teacher/exams/$examId'
      preLoaderRoute: typeof TeacherExamsExamIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results/$submissionId': {
      id: '/teacher/results/$submissionId'
      path: '/$submissionId'
      fullPath: '/teacher/results/$submissionId'
      preLoaderRoute: typeof TeacherResultsSubmissionIdRouteImport
      parentRoute: typeof TeacherResultsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalysisRoute: typeof DashboardAnalysisRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalysisRoute: DashboardAnalysisRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TeacherResultsRouteChildren {
  TeacherResultsSubmissionIdRoute: typeof TeacherResultsSubmissionIdRoute
}

const TeacherResultsRouteChildren: TeacherResultsRouteChildren = {
  TeacherResultsSubmissionIdRoute: TeacherResultsSubmissionIdRoute,
}

const TeacherResultsRouteWithChildren = TeacherResultsRoute._addFileChildren(
  TeacherResultsRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAnalysisRoute: typeof TeacherAnalysisRoute
  TeacherCreateExamRoute: typeof TeacherCreateExamRoute
  TeacherResultsRoute: typeof TeacherResultsRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherExamsExamIdRoute: typeof TeacherExamsExamIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnalysisRoute: TeacherAnalysisRoute,
  TeacherCreateExamRoute: TeacherCreateExamRoute,
  TeacherResultsRoute: TeacherResultsRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherExamsExamIdRoute: TeacherExamsExamIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExamRoute: ExamRoute,
  ExamsRoute: ExamsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TeacherRoute: TeacherRouteWithChildren,
  TypingRoute: TypingRoute,
  CodeExamExamIdRoute: CodeExamExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
